services:
  db:
    image: mysql:8
    platform: linux/amd64
    container_name: go-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: SL
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminiswhimsical
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_SL:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: myadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: http://localhost:8080/
    depends_on:
      - db

volumes:
  mysql_data_SL:

